"""Generate analysis/generated/results_snapshot.tex from committed results/*.json.

Every \\R{key} the paper uses is defined here from a result file, so no number
is typed into the manuscript by hand. Missing files simply leave their keys
undefined (the paper renders them in bold so they cannot slip through), which
is also what paper/verify_numbers.py checks.
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "results")
OUT = os.path.join(ROOT, "analysis", "generated", "results_snapshot.tex")


def load(name):
    p = os.path.join(RES, name)
    return json.load(open(p)) if os.path.exists(p) else None


def main():
    lines = ["% Auto-generated by analysis/make_snapshot.py. Do not edit by hand.\n"]
    defs = {}

    rh = load("raw_rhythm_analysis.json")
    if rh:
        a = rh["analysis"]
        defs["rhythmTasks"] = f"{a['n_tasks']:,}"
        defs["rhythmDomSharePct"] = f"{100*a['dom_harmonic_var_share']['median']:.1f}"
        defs["rhythmOverNoise"] = f"{a['dom_harmonic_var_share']['x_over_noise_floor']:.0f}"
        defs["rhythmOver30"] = f"{100*a['dom_harmonic_var_share']['frac_tasks_over_0.30']:.1f}"
        defs["rhythmDailyPct"] = f"{100*a['dominant_period_hours']['share_daily_12_24h']:.0f}"
        defs["rhythmMemCV"] = f"{a['memory_cv']['median']:.3f}"

    gains = []
    for scale, tag in ((0.5, "0p5"), (1.0, "1p0"), (2.0, "2p0"), (4.0, "4p0")):
        d = load(f"raw_packing_c{tag}.json")
        if not d:
            continue
        ps = d["per_scheme"]
        defs[f"packC{tag}rr"] = f"{ps['round_robin']['mean_fit']:.1f}"
        defs[f"packC{tag}legacy"] = f"{ps['legacy_desync']['mean_fit']:.1f}"
        defs[f"packC{tag}kur"] = f"{ps['repulsive']['mean_fit']:.1f}"
        defs[f"packC{tag}oracle"] = f"{ps['oracle']['mean_fit']:.1f}"
        gains.append(ps["repulsive"]["gain_vs_rr_pct"])
        defs["packSeeds"] = str(d["seeds"])
    if gains:
        defs["packMinGain"] = f"{min(gains):.1f}"
        defs["packMaxGain"] = f"{max(gains):.1f}"

    pl = load("raw_placement.json")
    if pl:
        r = pl["rules"]
        defs["placeTasks"] = f"{pl['provenance']['n_tasks']:,}"
        defs["placeSeeds"] = str(pl["provenance"]["seeds"])
        m = {"placePeak": "k8s_peak", "placeMean": "mean_overcommit",
             "placeWorst": "worst_bound_K24", "placeBlindZ4": "phase_blind_z4",
             "placeKur24Z4": "kuramoto_K24_z4"}
        for pre, key in m.items():
            defs[f"{pre}Nodes"] = f"{r[key]['nodes']:.1f}"
            defs[f"{pre}Over"] = f"{100*r[key]['overload']:.2f}"

    import glob
    oos_files = glob.glob(os.path.join(RES, "oos_placement_h*.json"))
    if oos_files:
        # pick the most robust run: most held-out test days, then longer history
        def _key(p):
            d = json.load(open(p)); pr = d["provenance"]
            return (pr.get("n_test_days", 0), pr.get("history", 0))
        oo = json.load(open(max(oos_files, key=_key)))
        s = oo["summary"]
        p = oo["provenance"]
        defs["oosHistory"] = str(p["history"])
        defs["oosDays"] = str(p.get("days", "?"))
        defs["oosSavingPct"] = f"{s['_node_saving_vs_peak_pct']:.1f}"
        kurkey = next((k for k in s if k.startswith("kuramoto") and k.endswith("z4")), None)
        m = {"oosPeak": "requests_peak", "oosBlind": "phase_blind_z4",
             "oosKur": kurkey, "oosOracle": "oracle_testday_z3"}
        for pre, key in m.items():
            if key and key in s:
                defs[f"{pre}Nodes"] = f"{s[key]['nodes']:.1f}"
                defs[f"{pre}Over"] = f"{100*s[key]['overload']:.2f}"

    ab = load("raw_placement_ablation.json")
    if ab:
        k = ab["K24_z4"]
        defs["ablLZ"] = f"{k['lz']['nodes']:.1f}"
        defs["ablBest"] = f"{k['best']['nodes']:.1f}"
        defs["ablFirst"] = f"{k['first']['nodes']:.1f}"

    for key, val in sorted(defs.items()):
        lines.append(f"\\defR{{{key}}}{{{val}}}\n")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.writelines(lines)
    print(f"wrote {len(defs)} macros to {OUT}")
    return defs


if __name__ == "__main__":
    main()
